### ISSUE TITLE
Makefiles are so 2000 :P 

### ISSUE THREAD

**Issue by ohz10** [JustWhit3/arsenalgear-cpp#1]
I'm interested in checking out `osmanip` and so I need `arsenalgear-cpp` due to a dependency.

My daily driver is `OpenBSD 7.1`... which isn't supported by your `Makefile`. After hacking up your `Makefile` to add support for OpenBSD, I was able to compile `arsenalgear-cpp` with `clang` and `gmake`. The tests appear to pass. 

```
$ bin/tests
[doctest] doctest version is "2.4.9"
[doctest] run with "--help" for options
Test================================================================================
[doctest] test cases: 21 | 21 passed | 0 failed | 0 skipped
[doctest] assertions: 59 | 59 passed | 0 failed | 
[doctest] Status: SUCCESS!
```

While I understand there's a certain appeal to the simplicity of `Makefiles`, I myself used them for my thesis project some 20 years ago until I discovered `scons`, they're almost always a bad idea IMHO. 

You would do well to consider adopting tools to generate your build files, e.g.:

- [CMake](https://cmake.org/)
- [Meson Build](https://mesonbuild.com/)

`CMake` is basically the _de facto_ standard for C++ projects (unfortunately). I personally prefer `meson`, but I've never used it on Windows so I'm not sure how it fairs on that OS. 

The power of generating the build scripts is that it allows developers to generate the build for their preferred environment / toolchain.

Let me know if you have any interest in `meson`, I'd be happy to put together a branch using it so you could check it out.

**Comment by JustWhit3** [comment]
Hi @ohz10 thank you very much for the suggestion.

You are completely right, in fact improving the building process is in my [todo](https://github.com/JustWhit3/osmanip#:~:text=graphics%20to%203D.-,System%20features,-Improve%20the%20compilation) list for [`osmanip`](https://github.com/JustWhit3/osmanip) and for the other C++ projects in general. However, I was thinking more about `CMake` than `Meson`, since it is more "standard" and I would prefer it in general.

If you have time and want to send a pull request with building improvements with CMake it would be a wonderful idea! Let me know.

Meanwhile I'll close this issue since it is not properly an issue, but a suggestion for an improvement.

Cheers.

**Comment by ohz10** [comment]
@JustWhit3 I'm sorry, I won't touch CMake anymore unless I'm being paid to do it; such is my disdain for the tool.

**Comment by eli-schwartz** [comment]
> `CMake` is basically the _de facto_ standard for C++ projects (unfortunately). I personally prefer `meson`, but I've never used it on Windows so I'm not sure how it fairs on that OS.

Meson works fine on Windows. Dependencies are a challenge on Windows regardless of build system, of course, but this project doesn't seem to have any regardless (those are *very* difficult to do robustly in pure Make, anyway...).
